version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: deivy
      MYSQL_PASSWORD: deivy
      MYSQL_DATABASE: dbnetdeal
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql